"""Added google calendar columns

Revision ID: 2ed55aaf3571
Revises: 
Create Date: 2025-12-08 00:49:43.296937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed55aaf3571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_token_expiry')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_access_token')

    # ### end Alembic commands ###
